"""Build the theme-owned Website, Marketing and Contact page collection.

Only the explicit targets below are written. Global chrome and Services are never touched.
Run from the repository root after editing this content source.
"""
from pathlib import Path
from html import escape as e
from PIL import Image

THEME = Path('wp-content/themes/extendable-child')
BASE = '/'  # Existing WordPress render filter adds the installation subdirectory.
ASSETS = BASE + 'wp-content/themes/extendable-child/assets/images/'

def image(name, alt, eager=False):
    width,height=Image.open(THEME/'assets/images'/name).size
    return f'<img src="{ASSETS}{name}" alt="{e(alt)}" width="{width}" height="{height}" decoding="async" loading="{"eager" if eager else "lazy"}"'+(' fetchpriority="high"' if eager else '')+'>'

def link(label, href='contact/', kind='primary'):
    return f'<a class="svc-button svc-button--{kind} wp-element-button" href="{BASE+href if not href.startswith("#") else href}">{label}<span aria-hidden="true">↗</span></a>'

def section(body, cls='', ident=''):
    return f'<section class="svc-section {cls}"'+(f' id="{ident}"' if ident else '')+f'><div class="svc-wrap">{body}</div></section>'

def heading(kicker, title, desc=''):
    return f'<div class="svc-heading" data-svc-reveal><div><p class="svc-kicker">{kicker}</p><h2>{title}</h2></div>'+ (f'<p>{desc}</p>' if desc else '')+'</div>'

def tabs(items):
    return '<div class="ft-tabs" role="group" aria-label="Preview options">'+''.join(f'<button type="button" data-ft-choice="{i}" aria-pressed="{"true" if i==0 else "false"}">{x[0]}</button>' for i,x in enumerate(items))+'</div>'

def preview(items, cls=''):
    return f'<div class="ft-interactive {cls}">{tabs(items)}'+''.join(f'<div class="ft-panel" data-ft-panel="{i}"'+(' hidden' if i else '')+f'>{body}</div>' for i,(_,body) in enumerate(items))+'</div>'

def window(body, label):
    return f'<div class="ft-window"><div class="ft-window-bar"><span aria-hidden="true">● ● ●</span><b>{label}</b><span>CONCEPT</span></div>{body}</div>'

def flow(items):
    return '<ol class="ft-flow">'+''.join(f'<li><span>0{i+1}</span><div><h3>{title}</h3><p>{desc}</p></div></li>' for i,(title,desc) in enumerate(items))+'</ol>'

def features(items, style='rail'):
    return f'<div class="ft-{style}">'+''.join(f'<article data-svc-reveal><span class="ft-index">0{i+1}</span><h3>{title}</h3><p>{desc}</p></article>' for i,(title,desc) in enumerate(items))+'</div>'

def cta(title, description, service):
    return section(f'<div class="ft-closing" data-svc-reveal><div><p class="svc-kicker">LET’S CREATE WHAT’S NEXT</p><h2>{title}</h2><p>{description}</p></div>{link("Let’s talk", "contact/?service="+service+"#project-inquiry")}</div>', 'ft-close-section')

def hero(slug, name, title, desc, photo, alt, widget='', mode='split', service='website', chips=()):
    bg=image(photo,alt,True)
    copy=f'<div class="ft-hero-copy"><p class="svc-kicker">FEG TECHNOVA / {name.upper()}</p><h1>{title}</h1><p class="ft-lead">{desc}</p><div class="svc-actions">{link("Discuss your project", "contact/?service="+service+"#project-inquiry")}{link("Explore the possibilities", "#features", "secondary")}</div><div class="ft-hero-chips">'+''.join(f'<span>{x}</span>' for x in chips)+'</div></div>'
    visual=f'<figure class="ft-hero-visual" data-svc-reveal>{widget}<figcaption>Illustrative concept · tailored to your business</figcaption></figure>' if widget else ''
    return f'<section class="svc-section ft-hero ft-hero--{mode}">{bg}<div class="svc-wrap ft-hero-layout">{copy}{visual}</div></section>'

def landing(slug, name, description, content):
    text=f'<!DOCTYPE html>\n<html lang="en"><head><meta charset="utf-8"><title>{e(name)} | FEG TechNova</title><meta name="description" content="{e(description)}"></head><body>\n<!-- HERO -->\n<div class="svc-page ft-page ft--{slug}">{content}</div>\n<!-- FOOTER -->\n</body></html>\n'
    # Keep generated HTML reviewable without requiring a formatter dependency.
    text=text.replace('><','>\n<')
    (THEME/'landing'/f'{slug}.html').write_text(text,encoding='utf-8')

def block(slug, content):
    text='<!-- wp:template-part {"slug":"header","tagName":"header"} /-->\n<!-- wp:group {"tagName":"main","className":"fegn-main svc-page ft-page ft--'+slug+'","layout":{"type":"default"}} -->\n<main id="fegn-main" class="wp-block-group fegn-main svc-page ft-page ft--'+slug+'">\n<!-- wp:html -->\n'+content.replace('><','>\n<')+'\n<!-- /wp:html -->\n</main>\n<!-- /wp:group -->\n<!-- wp:template-part {"slug":"footer","tagName":"footer"} /-->\n'
    (THEME/'templates'/f'page-{slug}.html').write_text(text,encoding='utf-8')

# WEBSITE — infrastructure, studio, commerce and a dedicated Shopify atelier.
domain_widget=window('<div class="ft-domain"><span class="ft-orbit ft-orbit--one"></span><span class="ft-orbit ft-orbit--two"></span><div class="ft-domain-core"><span aria-hidden="true">◎</span><strong>yourbrand.com</strong><small>A home for your next idea</small></div><span class="ft-domain-node ft-node-a">Domain</span><span class="ft-domain-node ft-node-b">Hosting</span><span class="ft-domain-node ft-node-c">SSL</span></div>','Your digital foundation')
domain_preview=preview([
 ('Business website','<p class="svc-kicker">A CLEAR STARTING POINT</p><h3>Your business, online.</h3><p>A domain, hosting environment, SSL setup and business email configuration shaped around your website.</p><div class="ft-stack"><span>Domain name</span><span>Website hosting</span><span>Business email</span></div>'),
 ('Online store','<p class="svc-kicker">READY FOR COMMERCE</p><h3>Give your store room to grow.</h3><p>Plan hosting resources, SSL and backups around your catalogue, checkout and expected traffic.</p><div class="ft-stack"><span>Store hosting</span><span>SSL setup</span><span>Backup planning</span></div>'),
 ('Existing website','<p class="svc-kicker">A CONSIDERED MOVE</p><h3>A carefully planned migration.</h3><p>Review your current setup, map DNS changes and plan file, database and email migration before switching.</p><div class="ft-stack"><span>Setup review</span><span>Migration plan</span><span>DNS configuration</span></div>')])
landing('domain-hosting','Domain & Hosting','Domain registration, website hosting, SSL and business email setup for your business.',hero('domain-hosting','Domain & Hosting','A strong home.<br><em>For every big idea.</em>','Your domain, hosting and business email—connected with care from the first step.','hero-cloud.webp','Server infrastructure for website hosting',domain_widget,'split',chips=('Domain registration','Hosting setup','Business email'))+section(heading('THE FOUNDATION','Everything starts with<br>the right address.','Build a considered foundation before your website goes live.')+f'<div class="ft-foundation"><div class="ft-address"><span>www.</span><strong>your next chapter</strong><span>.com</span><p>An example address. Domain availability is confirmed during consultation.</p></div>{features([("Your name, your presence","Choose a domain that feels right for your brand."),("Hosting that fits","Match the environment to your website’s needs."),("Connected essentials","Bring SSL, DNS and email configuration together.")],"compact")}</div>','', 'features')+section(f'<div class="svc-split"><div><p class="svc-kicker">THINK BEYOND THE DOMAIN</p><h2>A setup for<br>the way you work.</h2><p>Explore the essentials for a new website, an online store or a planned migration.</p></div>{domain_preview}</div>','svc-soft')+cta('Make your next move online.','Tell us what you’re building. We’ll help you plan the foundation.','website'))

web_widget=window('<div class="ft-browser-site"><div class="ft-browser-nav"><strong>STUDIO / ONE</strong><span>Work · About · Contact</span></div><div class="ft-browser-content"><small>DESIGNED WITH PURPOSE</small><h3>Ideas that<br>look forward.</h3><div class="ft-browser-art"><i></i><i></i><i></i></div><span class="ft-pill">Explore the collection ↗</span></div></div>','A website with a point of view')
web_view=preview([(label,f'<div class="ft-viewport ft-viewport--{mode}">{web_widget}</div><p class="ft-caption">{desc}</p>') for label,mode,desc in [('Desktop','desktop','Space for storytelling and confident navigation.'),('Tablet','tablet','A balanced composition for browsing on the move.'),('Mobile','mobile','The same story, focused for a smaller screen.')]],'ft-device-demo')
landing('web-design','Web Design & Development','Custom business website design and WordPress development with responsive layouts and clear customer journeys.',hero('web-design','Web Design & Development','Your website.<br><em>Your best first impression.</em>','Distinctive design. Clear customer journeys. Thoughtful development that brings your brand to life.','portfolio/studio.webp','A contemporary digital design workspace',web_widget,'studio',chips=('Custom design','WordPress development','Responsive experience'))+section(heading('BUILT AROUND YOUR BRAND','A website with<br>a point of view.','From your first impression to your next inquiry, every detail has a purpose.')+f'<div class="ft-design-spread"><div class="ft-type-study"><span>Aa</span><div><small>CLARITY / CHARACTER / CRAFT</small><h3>Good design<br>makes sense.</h3></div></div>{features([("Design that feels like you","A visual language shaped around your brand, audience and goals."),("Journeys that feel natural","Clear navigation, meaningful content and considered calls to action."),("Built to be managed","WordPress implementation with editable content and a practical handover.")],"editorial")}</div>', '', 'features')+section(f'<div class="svc-split"><div><p class="svc-kicker">ONE STORY. EVERY SCREEN.</p><h2>Beautiful wherever<br>it’s opened.</h2><p>Explore a responsive layout concept. Your site will be designed for real content and real devices.</p></div>{web_view}</div>','svc-soft')+section(heading('FROM CONVERSATION TO LAUNCH','A considered process.')+flow([('Discover','Define your audience, content and business goals.'),('Design','Shape the visual direction and key customer journeys.'),('Develop & refine','Build, review across screens and prepare your launch.')]))+cta('Let’s give your brand a better home.','Start with your idea. We’ll help shape the experience.','website'))

shop_items='<div class="ft-products"><div><div class="ft-product-art ft-art-bottle"></div><b>Daily essentials</b><small>Thoughtfully selected</small></div><div><div class="ft-product-art ft-art-vase"></div><b>Home objects</b><small>Made for everyday living</small></div><div><div class="ft-product-art ft-art-bag"></div><b>Carry collection</b><small>A little more considered</small></div></div>'
store=window('<div class="ft-store"><div class="ft-store-nav"><b>FORM & FIELD</b><span>Shop / Journal / Bag</span></div><div class="ft-store-banner"><span>OBJECTS FOR THE EVERYDAY</span><h3>Less ordinary.<br>More you.</h3></div>'+shop_items+'</div>','Storefront design concept')
commerce_preview=preview([('Discover','<div class="ft-shopping-scene"><span class="ft-scene-icon">⌕</span><h3>Find the right product.</h3><p>Clear categories, useful filters and search help customers explore your catalogue.</p><div class="ft-stack"><span>Collections</span><span>Search</span><span>Filters</span></div></div>'),('Consider','<div class="ft-shopping-scene"><span class="ft-scene-icon">◇</span><h3>Make the choice easier.</h3><p>Bring product photography, specifications, options and helpful details into one clear view.</p><div class="ft-stack"><span>Product details</span><span>Options</span><span>Related items</span></div></div>'),('Checkout','<div class="ft-shopping-scene"><span class="ft-scene-icon">▣</span><h3>Keep the next step clear.</h3><p>Plan cart, delivery information and payment integration around your market and platform.</p><div class="ft-stack"><span>Cart review</span><span>Delivery</span><span>Payment</span></div></div>')])
landing('ecommerce','Ecommerce Website','Ecommerce website design and development for product discovery, checkout and store management.',hero('ecommerce','Ecommerce Website','Turn browsing<br>into <em>possibility.</em>','A beautifully considered online store—from the first collection to the final checkout.','portfolio/commerce.webp','Online shopping on a laptop and smartphone',store,'commerce',chips=('Storefront design','Product catalogue','Checkout integration'))+section(heading('THE SHOPPING EXPERIENCE','Design the journey.<br>Not just the storefront.','A coherent experience makes products easier to explore and buying decisions clearer.')+f'<div class="ft-commerce-journey"><div class="ft-route"><span>Discover</span><i>→</i><span>Consider</span><i>→</i><span>Checkout</span></div>{commerce_preview}</div>', '', 'features')+section(f'<div class="ft-operations"><div><p class="svc-kicker">BEHIND EVERY BEAUTIFUL STORE</p><h2>A practical way<br>to run the business.</h2><p>Build the customer experience and the everyday operations together.</p></div>{features([("Catalogue management","Organise products, variants, collections and content."),("Payments & delivery","Connect suitable gateways and configure delivery options."),("Orders & handover","Set up order flows and show your team how to manage them.")],"compact")}</div>','svc-soft')+cta('Your next storefront starts here.','Tell us about your products, customers and preferred platform.','website'))

shopify_brand=preview([('Soft & minimal','<div class="ft-theme-sample ft-theme-minimal"><small>FORM & FIELD / COLLECTION</small><h3>Everyday,<br>beautifully.</h3><div class="ft-product-art ft-art-vase"></div><span>Warm neutrals. Quiet confidence.</span></div>'),('Bold & expressive','<div class="ft-theme-sample ft-theme-bold"><small>FORM & FIELD / COLLECTION</small><h3>Make room<br>for colour.</h3><div class="ft-product-art ft-art-bottle"></div><span>Strong type. A vivid point of view.</span></div>')])
landing('shopify','Shopify Development','Shopify store setup, theme customisation and ecommerce experience design for your brand.',hero('shopify','Shopify Development','A store that feels<br><em>unmistakably yours.</em>','Bring your brand to Shopify with considered theme design, clear product journeys and a practical store setup.','portfolio/motion.webp','Sculptural blue forms',store,'center',chips=('Shopify setup','Theme customisation','Store experience'))+section(heading('BRAND FIRST. COMMERCE READY.','Your platform.<br>Your personality.','Explore two visual directions for a fictional storefront. Your brand leads the design.')+f'<div class="ft-shopify-atelier">{shopify_brand}<div class="ft-atelier-notes"><span class="ft-big-mark">S<span>/</span></span>{features([("A considered theme","Customise layouts, typography and sections around your identity."),("An organised catalogue","Structure collections, variants and product information."),("A connected store","Configure suitable apps, payments and delivery settings.")],"editorial")}</div></div>','', 'features')+section(heading('THE LAUNCH EDIT','From setup to storefront.')+flow([('Shape the store','Map the catalogue, brand direction and required functionality.'),('Make it yours','Develop the theme experience and configure integrations.'),('Prepare to launch','Review checkout, mobile layouts and store management.')]),'svc-soft')+cta('Let’s shape your Shopify store.','Share your brand, catalogue and where you want to go next.','website'))

# The overview is a curated index, not a duplicate service landing page.
website_cards=[('01','domain-hosting','Domain & Hosting','The foundation','hero-cloud.webp','Website hosting infrastructure'),('02','web-design','Web Design & Development','The first impression','portfolio/studio.webp','Digital design studio'),('03','ecommerce','Ecommerce Website','The shopping experience','portfolio/commerce.webp','Ecommerce on multiple devices'),('04','shopify','Shopify Development','The brand-led store','portfolio/motion.webp','Sculptural blue abstract composition')]
website_content=hero('website','Website Services','A better place<br>for <em>your business online.</em>','From your first domain to your next storefront, build a digital presence with purpose.','hero-development.webp','A modern development workspace','', 'editorial',chips=('Infrastructure','Design & development','Commerce'))
website_content+=section(heading('EXPLORE WEBSITE SERVICES','Where do you<br>want to begin?','Choose the next chapter for your business.')+'<div class="ft-service-index">'+''.join(f'<a href="{BASE+slug}/" class="ft-index-card" data-svc-reveal>{image(photo,alt)}<div><span>{num} / {subtitle}</span><h3>{title}</h3><b aria-hidden="true">↗</b></div></a>' for num,slug,title,subtitle,photo,alt in website_cards)+'</div>','','features')
website_content+=section('<span id="fegn-web-services"></span>'+heading('A CONNECTED APPROACH','One brand.<br>A coherent experience.')+flow([('Start with the business','Understand your audience, content and day-to-day needs.'),('Make the experience clear','Connect design, navigation and functionality.'),('Build with care','Prepare a responsive website and a useful handover.')]),'svc-soft')+cta('Not sure where to start?','Tell us what you need your website to do. We’ll explore the right direction together.','website')
block('website',website_content)

# MARKETING — service-specific previews and editorial directions.
def message_card(channel, subject, copy, tone=''):
    return f'<div class="ft-message {tone}"><div class="ft-message-head"><span class="ft-message-avatar">F</span><div><b>YOUR BRAND</b><small>{channel} concept</small></div><span aria-hidden="true">•••</span></div><div class="ft-message-body"><h3>{subject}</h3><p>{copy}</p><span class="ft-message-action">Explore the collection ↗</span></div><p class="ft-caption">Example content · no message is sent</p></div>'

whatsapp=preview([('Welcome',message_card('WhatsApp','A warm first hello.','Thanks for joining us. Here’s a quick introduction to our collection—and how we can help.','ft-message--green')),('Launch',message_card('WhatsApp','Something new has arrived.','Discover the latest collection and find the details that matter to you.','ft-message--green')),('Follow-up',message_card('WhatsApp','Keep the conversation going.','Have a question about the collection? Reply here and let’s talk.','ft-message--green'))])
email=preview([('Editorial','<div class="ft-email"><div class="ft-email-meta"><b>From: Your brand</b><span>Subject: A fresh perspective for your week</span></div><div class="ft-email-paper"><small>THE WEEKLY EDIT</small><h3>Good things.<br>Worth opening.</h3><div class="ft-email-image"></div><p>A concise story, a thoughtful visual and one clear next step.</p><span class="ft-pill">Read the story ↗</span></div></div>'),('Product launch','<div class="ft-email"><div class="ft-email-meta"><b>From: Your brand</b><span>Subject: Meet your next everyday favourite</span></div><div class="ft-email-paper ft-email-launch"><small>JUST INTRODUCED</small><h3>A little more<br>extraordinary.</h3><div class="ft-product-art ft-art-bottle"></div><p>Introduce the product. Show the detail. Invite exploration.</p><span class="ft-pill">Explore what’s new ↗</span></div></div>')])
sms=preview([('SMS','<div class="ft-phone"><div class="ft-phone-top">Your brand <span>SMS concept</span></div><div class="ft-sms-bubble">A new collection is here. Explore the details at your website. Reply STOP to opt out.</div><div class="ft-phone-compose">A clear message. A useful next step.</div></div>'),('Voice','<div class="ft-phone ft-voice"><span class="ft-scene-icon">◉</span><h3>Your message,<br>with a human tone.</h3><div class="ft-wave" aria-hidden="true">'+''.join('<i></i>' for _ in range(24))+'</div><p>A concise introduction, a relevant offer and clear next steps.</p><small>Script concept · no audio or call is sent</small></div>')])
seo=preview([('Search intent','<div class="ft-search"><div class="ft-search-query">⌕ &nbsp; A question your customer is asking</div><small>SEARCH APPEARANCE CONCEPT</small><h3>A useful answer.<br>A clear next step.</h3><p>Your page title and description should explain what visitors will find and why it’s relevant.</p><div class="ft-search-tags"><span>Intent</span><span>Content</span><span>Clarity</span></div></div>'),('Page structure','<div class="ft-search"><div class="ft-search-query">⌕ &nbsp; Content with a clear structure</div><small>ON-PAGE CONTENT CONCEPT</small><h3>Make the answer<br>easy to find.</h3><p>Use descriptive headings, useful internal links and information that matches the customer’s question.</p><div class="ft-search-tags"><span>Headings</span><span>Internal links</span><span>Metadata</span></div></div>')])
tele=preview([('Open','<div class="ft-call-note"><small>01 / INTRODUCTION</small><h3>Start with<br>a relevant reason.</h3><p>Introduce the business clearly. Explain why you’re calling and ask whether it’s a suitable time.</p><div class="ft-script-line">“Hello, I’m calling from your brand…”</div></div>'),('Listen','<div class="ft-call-note"><small>02 / CONVERSATION</small><h3>Listen before<br>you recommend.</h3><p>Ask focused questions, understand the need and keep the discussion useful for the person on the call.</p><div class="ft-script-line">“What would be most useful for your team?”</div></div>'),('Follow through','<div class="ft-call-note"><small>03 / NEXT STEP</small><h3>Leave a clear<br>next step.</h3><p>Confirm the agreed follow-up and record the context for the next conversation.</p><div class="ft-script-line">“Would you like us to share the details?”</div></div>')])
social=preview([('Brand story','<div class="ft-social-post"><div class="ft-social-top"><span class="ft-message-avatar">F</span><b>Your brand</b><small>Post concept</small></div><div class="ft-social-art"><small>BEHIND THE BRAND</small><h3>Made with<br>intention.</h3><span>Stories worth sharing.</span></div><p>A thoughtful look at the people, process or purpose behind your business.</p></div>'),('Product story','<div class="ft-social-post"><div class="ft-social-top"><span class="ft-message-avatar">F</span><b>Your brand</b><small>Post concept</small></div><div class="ft-social-art ft-social-art--product"><small>THE EVERYDAY EDIT</small><h3>Small detail.<br>Big character.</h3><span>Meet the next collection.</span></div><p>Bring a product benefit to life with focused copy and a distinctive visual.</p></div>'),('Community','<div class="ft-social-post"><div class="ft-social-top"><span class="ft-message-avatar">F</span><b>Your brand</b><small>Post concept</small></div><div class="ft-social-art ft-social-art--community"><small>LET’S TALK</small><h3>What matters<br>to you?</h3><span>A conversation starts here.</span></div><p>Ask a relevant question and make space for a meaningful conversation.</p></div>')])
paid=preview([('Awareness','<div class="ft-campaign"><small>CAMPAIGN DIRECTION / AWARENESS</small><h3>Make the brand<br>easy to recognise.</h3><div class="ft-campaign-map"><span>Audience</span><i>→</i><span>Creative</span><i>→</i><span>Reach</span></div><p>Introduce the brand with a clear idea and consistent visuals. Review reach and engagement in context.</p></div>'),('Inquiries','<div class="ft-campaign"><small>CAMPAIGN DIRECTION / INQUIRIES</small><h3>Give interest<br>a clear next step.</h3><div class="ft-campaign-map"><span>Intent</span><i>→</i><span>Offer</span><i>→</i><span>Inquiry</span></div><p>Connect a relevant message with a focused landing page or inquiry flow. Review lead quality alongside cost.</p></div>'),('Sales','<div class="ft-campaign"><small>CAMPAIGN DIRECTION / SALES</small><h3>Connect the product<br>to the right moment.</h3><div class="ft-campaign-map"><span>Product</span><i>→</i><span>Message</span><i>→</i><span>Store</span></div><p>Plan product-led creative and a coherent shopping journey. Measurement depends on the platform and tracking setup.</p></div>')])
animation=preview([('2D storytelling','<div class="ft-motion-stage ft-motion-2d"><div class="ft-motion-shape"></div><div class="ft-motion-shape"></div><div class="ft-motion-shape"></div><p>Shapes. Rhythm. A clear story.</p><small>2D visual direction concept</small></div>'),('3D visualisation','<div class="ft-motion-stage ft-motion-3d"><div class="ft-motion-sculpture"><i></i><i></i><i></i></div><p>Form. Light. A new perspective.</p><small>CSS illustration of a 3D visual direction</small></div>')])
profile=window('<div class="ft-profile"><div class="ft-profile-cover"></div><div class="ft-profile-body"><span class="ft-message-avatar">F</span><h3>Your business</h3><p>A consistent presence, wherever customers find you.</p><div class="ft-profile-actions"><span>Website</span><span>Contact</span><span>Directions</span></div><div class="ft-profile-details"><span>Business name & category</span><span>Accurate contact details</span><span>Hours & visual identity</span></div><small>Illustrative profile · no verification badge or rating</small></div></div>','Business presence concept')
graphic=preview([('Identity','<div class="ft-graphic ft-graphic-identity"><small>BRAND IDENTITY / CONCEPT</small><h3>FORM<br><span>& FIELD</span></h3><div class="ft-swatches"><i></i><i></i><i></i><i></i></div><span>A clear visual language.</span></div>'),('Campaign','<div class="ft-graphic ft-graphic-campaign"><small>CAMPAIGN DESIGN / CONCEPT</small><h3>IDEAS<br>IN FULL<br><em>COLOUR.</em></h3><span>One idea. Multiple expressions.</span></div>'),('Print','<div class="ft-graphic ft-graphic-print"><div class="ft-print-sheet"><small>FORM & FIELD / BRAND EDIT</small><h3>Room<br>to think.</h3><div class="ft-print-rule"></div><p>A considered editorial system for your next brochure, profile or printed piece.</p></div></div>')])
film=preview([('Opening','<div class="ft-story-frame ft-frame-opening"><span>SCENE 01 / THE OPENING</span><h3>Set the scene.</h3><p>Introduce the world of your brand with a clear visual idea.</p></div>'),('Story','<div class="ft-story-frame ft-frame-story"><span>SCENE 02 / THE STORY</span><h3>Show what matters.</h3><p>Connect your people, products or process to the message.</p></div>'),('Closing','<div class="ft-story-frame ft-frame-closing"><span>SCENE 03 / THE CLOSING</span><h3>Leave a clear impression.</h3><p>Bring the story together with a considered brand moment.</p></div>')])

# Each record controls a unique hero composition, preview and supporting layout.
marketing=[
 dict(slug='whatsapp-marketing',name='WhatsApp Marketing',title='Better messages.<br><em>Closer conversations.</em>',desc='Turn WhatsApp into a thoughtful part of your customer communication—with relevant content and a clear campaign plan.',photo='portfolio/messaging.webp',alt='Hands using a smartphone beside a laptop',widget=whatsapp,mode='conversation',kicker='A CONVERSATION, NOT A WALL OF COPY',headline='Short messages.<br>Meaningful moments.',intro='Plan communications around the moments your audience cares about.',points=[('Welcome with purpose','Introduce your brand and set clear expectations.'),('Share something relevant','Build focused launches, offers and useful updates.'),('Make the next step easy','Give customers a clear way to explore or reply.')],style='rail',extraTitle='Consent is part of the experience.',extra='Use permission-based audiences, relevant frequency and a clear way to opt out. Campaign scope depends on the platform and available integrations.',extraPhoto='portfolio/planning.webp',close='Start a better conversation.'),
 dict(slug='email-marketing',name='Email Marketing',title='An inbox moment.<br><em>Worth opening.</em>',desc='Thoughtful email design, focused copy and a considered campaign rhythm for your brand.',photo='portfolio/planning.webp',alt='An open notebook in a planning workspace',widget=email,mode='paper',kicker='THE EMAIL EDIT',headline='One clear story.<br>One useful next step.',intro='Bring design, audience and content together in a coherent email experience.',points=[('Designed to be read','Clear hierarchy and responsive email layouts.'),('Written with purpose','Subject lines and copy that explain the value.'),('Planned for relevance','Audience segments, scheduling and campaign review.')],style='editorial',extraTitle='The right message at the right moment.',extra='Plan a welcome sequence, a useful newsletter or a focused product launch. Keep audience permission and unsubscribe options central.',extraPhoto='portfolio/design.webp',close='Let’s create your next inbox moment.'),
 dict(slug='sms-voice-marketing',name='SMS & Voice Marketing',title='A small message.<br><em>A clear connection.</em>',desc='Concise SMS campaigns and considered voice scripts that give your audience a useful next step.',photo='portfolio/messaging.webp',alt='A smartphone used for customer communication',widget=sms,mode='signal',kicker='CLARITY ON EVERY CHANNEL',headline='Say what matters.<br>Make it easy to act.',intro='Choose the format around the audience, message and campaign purpose.',points=[('Focused SMS copy','Keep the offer and next step clear in a compact format.'),('Considered voice scripts','A natural tone and concise structure for voice campaigns.'),('Practical campaign planning','Coordinate audience, schedule and available delivery tools.')],style='compact',extraTitle='Respect the person receiving it.',extra='Use permission-based contact lists, appropriate sending times and an accessible opt-out process. Confirm channel requirements before launch.',extraPhoto='portfolio/conversation.webp',close='Let’s make your message clear.'),
 dict(slug='seo',name='Search Engine Optimisation',title='Be useful.<br><em>Be discoverable.</em>',desc='Connect technical foundations, relevant content and clear page structure around the questions your customers ask.',photo='hero-data.webp',alt='Digital infrastructure supporting a technical website review',widget=seo,mode='search',kicker='BUILD RELEVANCE FROM THE INSIDE OUT',headline='Search starts<br>with understanding.',intro='A considered SEO approach connects the audience’s intent with a useful website.',points=[('Technical foundations','Review crawlability, site structure and performance issues.'),('Useful content','Map topics and search intent to clear, relevant pages.'),('On-page clarity','Refine titles, metadata, headings and internal links.')],style='rail',extraTitle='Measure, learn and refine.',extra='Review search visibility and visitor behaviour to guide the next improvements. SEO is an ongoing process; rankings and timelines are not guaranteed.',extraPhoto='portfolio/studio.webp',close='Give your website a clearer direction.'),
 dict(slug='telemarketing',name='Telemarketing',title='A human voice.<br><em>A better conversation.</em>',desc='Focused outreach planning, thoughtful call scripts and clear follow-up journeys for your business.',photo='portfolio/conversation.webp',alt='A customer communication professional wearing a headset',widget=tele,mode='human',kicker='PLAN THE CONVERSATION',headline='Listen closely.<br>Follow through clearly.',intro='Make each stage of the call useful to the person on the other end.',points=[('Prepare the outreach','Define the audience, purpose and relevant offer.'),('Shape the script','Create natural talking points and useful questions.'),('Plan the follow-up','Capture context and agree on a clear next step.')],style='editorial',extraTitle='A considered approach to outreach.',extra='Prioritise appropriate contact lists, respectful calling practices and clear opt-out handling. Agree on the campaign scope before outreach begins.',extraPhoto='portfolio/planning.webp',close='Let’s plan a useful conversation.'),
 dict(slug='social-media-management',name='Social Media Management',title='A recognisable brand.<br><em>Every time you show up.</em>',desc='Connect content planning, distinctive visuals and thoughtful community communication across your social channels.',photo='portfolio/design.webp',alt='A creative workspace with tablet and design tools',widget=social,mode='social',kicker='A COHERENT SOCIAL PRESENCE',headline='Less random posting.<br>More brand purpose.',intro='Give each piece of content a role in the wider story.',points=[('Content direction','Define themes, tone and a practical publishing rhythm.'),('Creative production','Create platform-appropriate visuals and concise captions.'),('Community & review','Coordinate responses and review content performance.')],style='rail',extraTitle='A calendar with room for real life.',extra='Balance planned brand stories, product content and timely conversations. Keep the content calendar useful rather than crowded.',extraPhoto='portfolio/planning.webp',close='Let’s shape your social presence.'),
 dict(slug='paid-advertising',name='Paid Advertising',title='A clear objective.<br><em>A considered campaign.</em>',desc='Bring audience, creative and landing experience together for paid search and social advertising.',photo='hero-data.webp',alt='Screens in a digital campaign analysis environment',widget=paid,mode='campaign',kicker='START WITH THE BUSINESS GOAL',headline='Give every campaign<br>a clear direction.',intro='Build the message and measurement plan around the outcome you want to explore.',points=[('Audience & channel','Choose a relevant audience and suitable advertising platforms.'),('Creative & destination','Connect the ad idea with a focused landing experience.'),('Tracking & refinement','Review available campaign data and refine the approach.')],style='compact',extraTitle='Think beyond the ad itself.',extra='A useful campaign depends on the offer, audience, creative and next step working together. Agree on budget, tracking and review criteria before launch.',extraPhoto='portfolio/commerce.webp',close='Let’s plan your next campaign.'),
 dict(slug='2d-3d-animation',name='2D & 3D Animation',title='Ideas in motion.<br><em>Stories with dimension.</em>',desc='Bring complex ideas, products and brand stories to life through considered 2D animation and 3D visualisation.',photo='portfolio/motion.webp',alt='Sculptural blue abstract forms',widget=animation,mode='motion',kicker='FIND THE RIGHT VISUAL LANGUAGE',headline='From a simple idea<br>to a moving story.',intro='Choose the style around the story—not the other way around.',points=[('2D storytelling','Explainers, motion graphics and character-led visual ideas.'),('3D visualisation','Product forms, environments and dimensional brand visuals.'),('A coherent finish','Connect pacing, typography, sound direction and brand identity.')],style='rail',extraTitle='Every frame begins with a plan.',extra='Develop the concept and storyboard before production. Review visual direction, pacing and output formats together.',extraPhoto='portfolio/design.webp',close='Let’s put your idea in motion.'),
 dict(slug='business-profile',name='Business Profile Setup',title='Your business.<br><em>Clearly represented.</em>',desc='Create a consistent, informative presence across relevant business profiles and social platforms.',photo='portfolio/studio.webp',alt='A professional digital workspace',widget=profile,mode='profile',kicker='THE DETAILS MAKE THE DIFFERENCE',headline='One business.<br>A consistent presence.',intro='Help customers recognise your brand and find accurate information.',points=[('Business essentials','Align your name, contact details, category and hours.'),('Brand presentation','Prepare profile imagery, descriptions and visual consistency.'),('Setup & handover','Configure relevant profiles and explain ongoing management.')],style='editorial',extraTitle='Clear information builds a better experience.',extra='Review your current listings, remove inconsistencies and prepare the information each platform needs. Approval and verification remain subject to platform requirements.',extraPhoto='portfolio/planning.webp',close='Let’s make your business easier to find.'),
 dict(slug='graphic-design',name='Creative Graphic Design',title='Make the idea<br><em>impossible to overlook.</em>',desc='Distinctive visual identities, campaign graphics and editorial design that give your brand a coherent point of view.',photo='portfolio/design.webp',alt='Graphic design tools in a creative workspace',widget=graphic,mode='graphic',kicker='DESIGN WITH CHARACTER',headline='A visual language.<br>Not a collection of files.',intro='Create a coherent system that works across the places your brand appears.',points=[('Brand identity','Shape typography, colour and visual elements around your brand.'),('Digital creative','Campaign assets and social visuals designed for their channels.'),('Print & editorial','Business profiles, brochures and considered print layouts.')],style='compact',extraTitle='From the first sketch to the final detail.',extra='Explore a visual direction, refine the design and prepare suitable deliverables for the agreed channels. Every format should feel like the same brand.',extraPhoto='portfolio/planning.webp',close='Let’s give your ideas a visual voice.'),
 dict(slug='corporate-video',name='Corporate Video / OVC',title='Your story.<br><em>Made to be seen.</em>',desc='Corporate films and online video commercials shaped around a clear message, strong visual direction and your brand.',photo='portfolio/film.webp',alt='Professional video camera on a tripod in a studio',widget=film,mode='cinema',kicker='BEFORE THE CAMERA ROLLS',headline='Find the story.<br>Then frame it beautifully.',intro='A clear concept gives every scene a reason to be there.',points=[('Concept & script','Find the message, audience and narrative direction.'),('Production planning','Shape the storyboard, locations and required footage.'),('Edit & delivery','Bring the story together with pacing, graphics and suitable formats.')],style='editorial',extraTitle='One story. The right formats.',extra='Plan your corporate film, product story or online commercial around where it will be watched. Agree on scope, production needs and delivery formats together.',extraPhoto='portfolio/studio.webp',close='Let’s frame your next brand story.')
]

for idx,p in enumerate(marketing):
    content=hero(p['slug'],p['name'],p['title'],p['desc'],p['photo'],p['alt'],p['widget'],p['mode'],'marketing',('Strategy','Creative','Thoughtful delivery'))
    # Alternating art-directed editorial structures with service-specific visual motifs.
    feature=heading(p['kicker'],p['headline'],p['intro'])
    if p['slug']=='social-media-management':
        feature+='<div class="ft-content-calendar"><span>THE CONTENT RHYTHM</span><div><b>Brand story</b><b>Product detail</b><b>Useful insight</b><b>Conversation</b></div></div>'
    elif p['slug']=='2d-3d-animation':
        feature+='<div class="ft-timeline" aria-hidden="true"><span>Concept</span><i></i><span>Storyboard</span><i></i><span>Motion</span><i></i><span>Finish</span></div>'
    elif p['slug']=='graphic-design':
        feature+='<div class="ft-design-rule"><b>Aa</b><span>Type / Colour / Composition</span><i></i><i></i><i></i></div>'
    elif p['slug']=='corporate-video':
        feature+='<div class="ft-film-strip" aria-hidden="true"><span>STORY</span><span>LIGHT</span><span>FRAME</span><span>FEELING</span></div>'
    feature+=features(p['points'],p['style'])
    content+=section(feature,'','features')
    extra=f'<div class="svc-split ft-editorial-split"><figure class="svc-photo" data-svc-reveal>{image(p["extraPhoto"],"Creative planning and production workspace")}<figcaption>{p["name"]} / A considered approach</figcaption></figure><div data-svc-reveal><p class="svc-kicker">THE THOUGHT BEHIND THE WORK</p><h2>{p["extraTitle"]}</h2><p>{p["extra"]}</p><div class="ft-note"><span aria-hidden="true">↗</span><p>Start with a conversation about your audience, goals and scope.</p></div></div></div>'
    if p['slug']=='seo':
        diagram='<div class="ft-site-map"><b>Your website</b><div><span>Site structure</span><span>Useful content</span><span>Internal links</span></div><p>Intent → Useful answer → Clear next step</p></div>'
        extra=f'<div class="svc-split"><div><p class="svc-kicker">A CONNECTED SEARCH STRATEGY</p><h2>{p["extraTitle"]}</h2><p>{p["extra"]}</p></div>{diagram}</div>'
    elif p['slug']=='paid-advertising':
        extra=f'<div class="ft-campaign-board"><div><p class="svc-kicker">THE WHOLE CAMPAIGN</p><h2>{p["extraTitle"]}</h2><p>{p["extra"]}</p></div><div class="ft-campaign-brief"><span>THE PLANNING BOARD</span><dl><div><dt>Purpose</dt><dd>A clear business objective</dd></div><div><dt>Creative</dt><dd>A message with a point of view</dd></div><div><dt>Destination</dt><dd>A useful next step</dd></div><div><dt>Review</dt><dd>Context, measurement and learning</dd></div></dl></div></div>'
    elif p['slug'] in ('email-marketing','sms-voice-marketing','whatsapp-marketing'):
        labels={'email-marketing':[('Permission','An audience that wants to hear from you.'),('Relevance','Content with a reason to be in the inbox.'),('Rhythm','A considered frequency and clear opt-out.')],'sms-voice-marketing':[('Audience','Permission-based contacts.'),('Timing','An appropriate moment.'),('Choice','A clear way to opt out.')],'whatsapp-marketing':[('Permission','Start with a willing audience.'),('Purpose','Make each message useful.'),('Choice','Respect how customers want to connect.')]}
        extra=f'<div class="ft-principles-intro"><p class="svc-kicker">THOUGHTFUL COMMUNICATION</p><h2>{p["extraTitle"]}</h2><p>{p["extra"]}</p></div><div class="ft-principles">'+''.join(f'<div><span aria-hidden="true">0{i+1}</span><h3>{title}</h3><p>{desc}</p></div>' for i,(title,desc) in enumerate(labels[p['slug']]))+'</div>'
    elif p['slug']=='2d-3d-animation':
        extra=f'<div class="ft-motion-process"><div><p class="svc-kicker">THE PRODUCTION STORY</p><h2>{p["extraTitle"]}</h2><p>{p["extra"]}</p></div><div class="ft-frame-sequence" aria-hidden="true"><span>01<i></i></span><span>02<i></i></span><span>03<i></i></span></div></div>'
    elif p['slug'] in ('graphic-design','corporate-video'):
        extra=f'<div class="ft-wide-editorial">{image(p["extraPhoto"],"Creative production workspace")}<div><p class="svc-kicker">THE CREATIVE DIRECTION</p><h2>{p["extraTitle"]}</h2><p>{p["extra"]}</p></div></div>'
    content+=section(extra,'svc-soft'+(' ft-reverse' if idx%2 else ''))
    content+=cta(p['close'],'Share your idea. We’ll explore the right creative direction together.','marketing')
    landing(p['slug'],p['name'],p['desc'],content)

# CONTACT — exact existing form field contract, accurate details and unaltered QR.
contact_hero=hero('contact','Contact','Great work starts<br>with <em>a conversation.</em>','A new idea, a better website or your next campaign—tell us what you have in mind.','about-story-team.jpg','A team collaborating around a table','', 'contact',chips=('Websites & technology','Marketing & creative','Let’s build together'))
contact_hero=contact_hero.replace('href="'+BASE+'contact/?service=website#project-inquiry"','href="#project-inquiry"').replace('Discuss your project','Tell us about your project').replace('href="#features"','href="#contact-details"').replace('Explore the possibilities','Find us')
services=[('erp','ERP Development'),('saas','SaaS Development'),('web','Web Application Development'),('website','Website Design & Development'),('mobile','Mobile App Development'),('crm','CRM Solutions'),('uiux','UI/UX Design'),('ai','AI Automation'),('chatbot','AI Chatbot'),('marketing','Marketing & Creative'),('other','Other / Let’s discuss')]
fields=[('full_name','fegn-name','Full name','text','name',True),('email','fegn-email','Email address','email','email',True),('phone','fegn-phone','Phone number','tel','tel',True),('company','fegn-company','Company','text','organization',False)]
form='<form id="fegn-contact-form" class="ft-form" method="post" novalidate><div id="fegn-form-status" class="fegn-form-status" role="status" aria-live="polite" hidden></div><div class="ft-form-grid">'
for name,ident,label,typ,auto,required in fields:
    form+=f'<div class="ft-field"><label for="{ident}">{label} <span>{"*" if required else "(optional)"}</span></label><input id="{ident}" name="{name}" type="{typ}" autocomplete="{auto}"'+(' required' if required else '')+'></div>'
form+='<div class="ft-field ft-field--full"><label for="fegn-service">What can we help with? <span>*</span></label><select id="fegn-service" name="service" required><option value="">Choose a service</option>'+''.join(f'<option value="{value}">{label}</option>' for value,label in services)+'</select></div><div class="ft-field ft-field--full"><label for="fegn-message">Tell us about your project <span>*</span></label><textarea id="fegn-message" name="message" rows="5" required placeholder="Your idea, goals or what you’d like to improve…"></textarea></div></div><div class="ft-honeypot" aria-hidden="true"><label for="fegn-company-website">Leave this field empty</label><input type="text" id="fegn-company-website" name="fegn_company_website" tabindex="-1" autocomplete="off"></div><div class="ft-form-bottom"><p>Fields marked * are required.<br>Your details help us respond to your inquiry.</p><button id="fegn-form-submit-btn" type="submit" class="svc-button svc-button--primary">Send inquiry <span aria-hidden="true">↗</span></button></div><noscript><p>Please enable JavaScript to use this form, or email <a href="mailto:info@fegtechnova.com">info@fegtechnova.com</a>.</p></noscript></form>'
contact_content=contact_hero+section(f'<div class="ft-contact-layout"><aside class="ft-contact-intro" data-svc-reveal><p class="svc-kicker">YOUR NEXT CHAPTER</p><h2>What are you<br>thinking about?</h2><p>You don’t need a finished brief. A few details about your business and what you want to achieve are a good start.</p><div class="ft-interest" role="group" aria-label="Choose your area of interest"><button type="button" data-ft-service="website">A website ↗</button><button type="button" data-ft-service="web">A digital product ↗</button><button type="button" data-ft-service="marketing">Marketing & creative ↗</button><button type="button" data-ft-service="other">Something else ↗</button></div><div class="ft-contact-tip"><span>01 / START SIMPLE</span><p>What you’re building.<br>Who it’s for.<br>What success would look like.</p></div></aside><div class="ft-form-card" data-svc-reveal><div class="ft-form-heading"><span class="ft-message-avatar">↗</span><div><h3>Let’s hear your idea.</h3><p>Share a little context to start the conversation.</p></div></div>{form}</div></div>','','project-inquiry')
contact_content+=section(f'<div class="ft-contact-details"><div><p class="svc-kicker">COME SAY HELLO</p><h2>A direct line.<br>A real conversation.</h2><div class="ft-contact-links"><a href="tel:+8801886800991"><span>CALL US</span><strong>01886800991</strong><b aria-hidden="true">↗</b></a><a href="mailto:info@fegtechnova.com"><span>EMAIL US</span><strong>info@fegtechnova.com</strong><b aria-hidden="true">↗</b></a><div><span>VISIT OUR OFFICE</span><strong>Green Satmahal, 4th Floor</strong><p>Outer Circular Road, Dhaka 1217</p></div></div></div><div class="ft-qr-card"><div><p class="svc-kicker">KEEP US CLOSE</p><h3>FEG TechNova<br>on Linktree.</h3><p>Scan the official company QR code or open the link below.</p></div><a class="ft-qr-image" href="https://linktr.ee/fegtechnova" aria-label="Open FEG TechNova on Linktree">{image("feg-technova-official-qr.png","Official FEG TechNova QR code linking to https://linktr.ee/fegtechnova")}</a><a class="ft-qr-link" href="https://linktr.ee/fegtechnova">Open FEG TechNova on Linktree <span aria-hidden="true">↗</span></a></div></div>','svc-soft','contact-details')
block('contact',contact_content)
print('Built 15 landing files and Website + Contact block templates.')

