const {chromium}=require(process.env.TEMP+'/zrc-browser-review/node_modules/playwright');
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert');
const out=path.join(process.env.TEMP,'fegn-experience-review');fs.mkdirSync(out,{recursive:true});
const theme='wp-content/themes/extendable-child',base='http://localhost/fegtechnova';
const fingerprint=()=>({text:document.querySelector('main').textContent.replace(/\s+/g,' ').trim(),links:[...document.querySelectorAll('main a')].map(a=>a.getAttribute('href')),images:[...document.querySelectorAll('main img')].map(a=>[a.getAttribute('src'),a.getAttribute('alt')]),form:document.querySelector('#fegn-contact-form')?.outerHTML,sectionPadding:[...document.querySelectorAll('main>.svc-section,main>.fegn-section')].map(e=>[getComputedStyle(e).paddingTop,getComputedStyle(e).paddingBottom])});
(async()=>{
 const b=await chromium.launch({channel:'msedge',headless:true}),p=await b.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
 if(process.argv.includes('baseline')){const pages={};for(const slug of ['', 'contact']){await p.goto(base+'/'+slug+'/',{waitUntil:'networkidle'});pages[slug||'home']=await p.evaluate(fingerprint)}const files=[];for(const dir of ['templates','landing','assets/css','assets/js','parts'])for(const f of fs.readdirSync(theme+'/'+dir)){let name=theme+'/'+dir+'/'+f;if(fs.statSync(name).isFile()&&!f.includes('experience'))files.push(name)}files.push('wp-content/plugins/feg-technova-core/includes/contact-form.php');fs.writeFileSync(path.join(out,'baseline.json'),JSON.stringify({pages,files:Object.fromEntries(files.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')]))},null,2));console.log('Experience baseline saved.');await b.close();return;}
 const baseline=JSON.parse(fs.readFileSync(path.join(out,'baseline.json'))),checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));const check=(name,ok)=>{assert(ok,name);checks.push(name)};
 for(const [file,expected]of Object.entries(baseline.files))check('Unchanged '+file,crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')===expected);
 for(const width of [1440,768,390,320])for(const color of ['light','dark'])for(const slug of ['', 'contact']){
  await p.setViewportSize({width,height:1000});await p.goto(base+'/'+slug+'/',{waitUntil:'networkidle'});await p.evaluate(t=>document.documentElement.setAttribute('data-theme',t),color);
  const actual=await p.evaluate(fingerprint),expected=baseline.pages[slug||'home'];for(const field of ['text','links','images','form'])check(`Preserved ${slug||'home'} ${field}/${width}/${color}`,JSON.stringify(actual[field])===JSON.stringify(expected[field]));
  check(`No overflow ${slug||'home'}/${width}/${color}`,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));check(`One H1 ${slug||'home'}/${width}/${color}`,await p.locator('main h1').count()===1);
  if(slug)check(`42px Contact sections ${width}/${color}`,actual.sectionPadding.every(a=>a[0]==='42px'&&a[1]==='42px'));
  await p.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=650){scrollTo({top:y,behavior:'instant'});await new Promise(r=>setTimeout(r,70))}scrollTo({top:0,behavior:'instant'})});
  check(`Images loaded ${slug||'home'}/${width}/${color}`,await p.locator('main img').evaluateAll(images=>images.every(i=>i.complete&&i.naturalWidth)));
  if(width!==320)await p.screenshot({path:path.join(out,`${slug||'home'}-${width}-${color}.png`),fullPage:true});
 }
 for(const slug of ['erp-development','graphic-design','website']){await p.goto(base+'/'+slug+'/',{waitUntil:'networkidle'});check('Enhancement excluded '+slug,await p.locator('link[href*="fegn-experience.css"]').count()===0&&await p.locator('script[src*="fegn-experience.js"]').count()===0)}
 await p.goto(base+'/contact/?service=website#project-inquiry',{waitUntil:'networkidle'});check('Service CTA preselection',await p.locator('#fegn-service').inputValue()==='website');await p.locator('#fegn-form-submit-btn').click();check('Required-field validation',/full name/.test(await p.locator('#fegn-form-status').innerText()));
 await p.locator('#fegn-name').fill('Local Animation Review');await p.locator('#fegn-email').fill('ui-review@example.com');await p.locator('#fegn-phone').fill('01886800991');await p.locator('#fegn-message').fill('Localhost animation and interface verification.');const response=p.waitForResponse(r=>r.url().includes('admin-ajax.php')&&r.request().method()==='POST');await p.locator('#fegn-form-submit-btn').click();check('Existing localhost submission', (await (await response).json()).success===true);await p.waitForFunction(()=>!document.querySelector('#fegn-form-submit-btn').disabled);check('Form resets after success',await p.locator('#fegn-name').inputValue()==='');
 const normal=await b.newContext({viewport:{width:1440,height:1000}}),animated=await normal.newPage();await animated.goto(base+'/',{waitUntil:'networkidle'});check('Custom Homepage hero entrance hook',await animated.locator('main').getAttribute('data-experience')==='home');await animated.waitForFunction(()=>document.querySelector('.fegn-hero').classList.contains('is-ready'));const pause=animated.locator('.fegn-hero__pause');await pause.click();check('Existing pause controls new motion',await animated.locator('.fegn-hero__bg-slide--1').evaluate(e=>getComputedStyle(e).animationPlayState.split(',').every(x=>x.trim()==='paused')));await pause.click();check('Background motion resumes',await animated.locator('.fegn-hero__bg-slide--1').evaluate(e=>getComputedStyle(e).animationPlayState.includes('running')));
 const card=animated.locator('.fegn-capabilities__card').first();await card.scrollIntoViewIfNeeded();await animated.waitForTimeout(900);check('Scroll reveal completes',await card.evaluate(e=>!e.hasAttribute('data-xp-pending')&&getComputedStyle(e).opacity==='1'));await animated.emulateMedia({reducedMotion:'reduce'});check('Reduced motion stops background animation',await animated.locator('.fegn-hero__bg-slide--1').evaluate(e=>getComputedStyle(e).animationName==='none'));check('Reduced motion exposes all content',await animated.locator('[data-xp-pending]').count()===0);await normal.close();
 const plain=await b.newContext({javaScriptEnabled:false,viewport:{width:390,height:900}}),staticPage=await plain.newPage();for(const slug of ['', 'contact']){await staticPage.goto(base+'/'+slug+'/',{waitUntil:'networkidle'});check('No-JS heading visible '+slug,await staticPage.locator('main h1').isVisible())}await plain.close();
 check('No runtime errors',errors.length===0);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,errors,out},null,2));await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
